### ISSUE TITLE
node server.js issue

### ISSUE THREAD

**Issue by costargc** [mgilliland23/quantla#34]
node server.js is showing an google authentication issue... require further investigation.

Error: Could not load the default credentials. Browse to https://cloud.google
.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (D:\Server\Code\PROJECT\quantla\
node_modules\google-auth-library\build\src\auth\googleauth.js:161:19)

**Comment by mgilliland23** [comment]
I am also receiving this error, although I am able to log the username and email address of the user that is logged in on the front end, so Auth seems to be working. Login is working fine as well so this seems like a non-breaking issue at the moment

**Comment by mgilliland23** [comment]
I believe this is fixed with the last commit. I'm going to mark as closed for now...
