### ISSUE TITLE
tensorflow model order is wrong... its fitting the model to make a prediction (user needs to wait for a response)

### ISSUE THREAD

**Issue by costargc** [mgilliland23/quantla#48]
So the way we implemented tensor flow for now... every new data, will trigger a model fit.
That means that user will need to wait for a new model to trained to have the date... when we were running this locally the model would fit < 10s so that was not an issue for the user as they would get the results every 30s.

but with the AWS hosting model takes as much as 2min to be produced.

A way to solve this is the keep in memory the old model... and do a model.predict based on the previous mode ... after that we .dispose() the tensors and fit again.

current order: 
start: no need
loop: get data current >> create model >> fit model >> predict >> dispose

proposed order: 
start: get data current >> create model >> fit model >> predict
loop: data current >> predict  >> dispose >> create new model >> fit model

**Comment by mgilliland23** [comment]
If the proposed changes don't provide an adequate solution, maybe we should look into hosting the model on a separate AWS service such as Lambda.

**Comment by costargc** [comment]
changes did the job! 👍  🥇
