### ISSUE TITLE
Date is being truncated on mobile

### ISSUE THREAD

**Issue by mgilliland23** [mgilliland23/quantla#64]
The date is being truncated on my iphone 8 to the point where the only thing I can see is Sun, Aug.... 

We should consider displaying only the hour and minutes ex.:  11:35 PM

And also adjusting the column width for some tables

**Comment by costargc** [comment]
column width adjusted for now... I do agree we should move if to a short version. 
suggestion > DD/MMM hh:mm

**Comment by mgilliland23** [comment]
Fixed in latest pull request
